# Assignment 3

In [1]:
import pandas as pd
import numpy as np

# Load MovieLens 100K dataset into a dataframe of pandas
names = ['user_id', 'item_id', 'rating', 'timestamp']
df = pd.read_csv('ml-100k/u.data', sep='\t', names=names)
df.head()

   user_id  item_id  rating  timestamp
0      196      242       3  881250949
1      186      302       3  891717742
2       22      377       1  878887116
3      244       51       2  880606923
4      166      346       1  886397596

In [2]:
# Select 500 most active users and 500 most active items from the dataset
n_most_active_users = 500
n_most_active_items = 500

user_ids = df.groupby('user_id').count().sort_values(by='rating', ascending=False).head(n_most_active_users).index
item_ids = df.groupby('item_id').count().sort_values(by='rating', ascending=False).head(n_most_active_items).index
df = df[(df['user_id'].isin(user_ids)) & (df['item_id'].isin(item_ids))]

In [3]:
# Map new internal ID for items
i_ids = df['item_id'].unique().tolist()
item_dict = dict(zip(i_ids, [i for i in range(len(i_ids))]))
df['item_id'] = df['item_id'].map(item_dict)

# Split Dataset

In [4]:
# The number of training users and active users
n_training_users = 300
n_active_users = n_most_active_users - n_training_users

# The number of GIVEN ratings for active users
GIVEN = 20

# Randomly select users from the most active users as training set
random_uids = np.random.choice(df.user_id.unique(), n_training_users, replace=False)
train_df = df[df['user_id'].isin(random_uids)]
# Map new internal ID for all users in the training set
u_ids = train_df['user_id'].unique().tolist()
user_dict = dict(zip(u_ids, [i for i in range(len(u_ids))]))
train_df['user_id'] = train_df['user_id'].map(user_dict)

# The rest of users are active users for testing
remain_df = df[~df['user_id'].isin(random_uids)]
# Map new internal ID for all active users
u_ids = remain_df['user_id'].unique().tolist()
user_dict = dict(zip(u_ids, [i for i in range(len(u_ids))]))
remain_df['user_id'] = remain_df['user_id'].map(user_dict)

# Randomly select GIVEN ratings for active users
active_df = remain_df.groupby('user_id').sample(n=GIVEN, random_state=1024)

test_df = remain_df[~remain_df.index.isin(active_df.index)]

<ipython-input-4-fb140fbf3b12>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df['user_id'] = train_df['user_id'].map(user_dict)
<ipython-input-4-fb140fbf3b12>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  remain_df['user_id'] = remain_df['user_id'].map(user_dict)

In [5]:
# Convert the format of datasets to matrices
df_zeros = pd.DataFrame({'user_id': np.tile(np.arange(0, n_training_users), n_most_active_items), 'item_id': np.repeat(np.arange(0, n_most_active_items), n_training_users), 'rating': 0})
train_ds = df_zeros.merge(train_df, how='left', on=['user_id', 'item_id']).fillna(0.).pivot_table(values='rating_y', index='user_id', columns='item_id')

df_zeros = pd.DataFrame({'user_id': np.tile(np.arange(0, n_active_users), n_most_active_items), 'item_id': np.repeat(np.arange(0, n_most_active_items), n_active_users), 'rating': 0})
active_ds = df_zeros.merge(active_df, how='left', on=['user_id', 'item_id']).fillna(0.).pivot_table(values='rating_y', index='user_id', columns='item_id')
test_ds = df_zeros.merge(test_df, how='left', on=['user_id', 'item_id']).fillna(0.).pivot_table(values='rating_y', index='user_id', columns='item_id')

train_ds, active_ds, test_ds

(item_id  0    1    2    3    4    5    6    7    8    9    ...  490  491  492  \
 user_id                                                    ...
 0        3.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0  0.0  ...  0.0  0.0  0.0
 1        0.0  2.0  0.0  4.0  0.0  4.0  4.0  0.0  0.0  2.0  ...  0.0  4.0  4.0
 2        0.0  0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0  4.0  ...  0.0  0.0  0.0
 3        4.0  0.0  5.0  0.0  0.0  3.0  4.0  2.0  0.0  2.0  ...  0.0  2.0  0.0
 4        3.0  0.0  4.0  0.0  0.0  3.0  2.0  2.0  0.0  5.0  ...  0.0  4.0  0.0
 ...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
 295      0.0  0.0  0.0  0.0  0.0  0.0  0.0  5.0  4.0  5.0  ...  0.0  0.0  4.0
 296      0.0  0.0  5.0  4.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0
 297      4.0  0.0  3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
 298      0.0  0.0  0.0  3.0  0.0  0.0  0.0  4.0  0.0  0.0  ...  0.0  0.0  5.0
 299      0.0  0.0  0.0  0.0  0.0  0.0  0.0  3.0  3.0  0.0  ...  4.0  0.0  0.0

 item_id  493  494  495  496  497  498  499
 user_id
 0        0.0  0.0  0.0  4.0  0.0  3.0  0.0
 1        0.0  3.0  3.0  0.0  0.0  0.0  0.0
 2        0.0  0.0  0.0  0.0  0.0  0.0  0.0
 3        0.0  0.0  0.0  0.0  4.0  0.0  0.0
 4        0.0  0.0  0.0  0.0  0.0  0.0  0.0
 ...      ...  ...  ...  ...  ...  ...  ...
 295      0.0  4.0  2.0  3.0  0.0  0.0  0.0
 296      0.0  0.0  0.0  0.0  0.0  1.0  0.0
 297      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 298      0.0  0.0  3.0  0.0  0.0  0.0  0.0
 299      5.0  0.0  0.0  3.0  0.0  0.0  0.0

 [300 rows x 500 columns],
 item_id  0    1    2    3    4    5    6    7    8    9    ...  490  491  492  \
 user_id                                                    ...
 0        0.0  0.0  4.0  0.0  0.0  0.0  0.0  4.0  0.0  0.0  ...  0.0  0.0  0.0
 1        4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
 2        0.0  0.0  5.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
 3        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
 4        0.0  0.0  0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0  ...  3.0  0.0  0.0
 ...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
 195      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0  ...  0.0  0.0  0.0
 196      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
 197      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
 198      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
 199      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0

 item_id  493  494  495  496  497  498  499
 user_id
 0        0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1        0.0  0.0  0.0  0.0  0.0  0.0  0.0
 2        0.0  0.0  0.0  0.0  0.0  0.0  2.0
 3        0.0  0.0  0.0  0.0  0.0  0.0  0.0
 4        0.0  0.0  0.0  0.0  0.0  0.0  0.0
 ...      ...  ...  ...  ...  ...  ...  ...
 195      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 196      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 197      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 198      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 199      0.0  0.0  0.0  0.0  0.0  0.0  0.0

 [200 rows x 500 columns],
 item_id  0    1    2    3    4    5    6    7    8    9    ...  490  491  492  \
 user_id                                                    ...
 0        0.0  0.0  0.0  4.0  4.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
 1        0.0  0.0  0.0  2.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
 2        4.0  0.0  0.0  0.0  1.0  0.0  0.0  2.0  0.0  0.0  ...  0.0  0.0  0.0
 3        0.0  0.0  0.0  0.0  5.0  5.0  0.0  3.0  5.0  0.0  ...  0.0  4.0  0.0
 4        0.0  0.0  0.0  0.0  0.0  0.0  4.0  4.0  0.0  5.0  ...  0.0  0.0  0.0
 ...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
 195      4.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0  3.0  ...  0.0  0.0  4.0
 196      0.0  0.0  0.0  0.0  0.0  0.0  0.0  3.0  0.0  4.0  ...  0.0  0.0  0.0
 197      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
 198      0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
 199      0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  3.0  4.0  0.0

 item_id  493  494  495  496  497  498  499
 user_id
 0        0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1        0.0  0.0  0.0  0.0  0.0  0.0  0.0
 2        4.0  1.0  0.0  0.0  0.0  0.0  0.0
 3        0.0  0.0  0.0  3.0  0.0  3.0  0.0
 4        0.0  5.0  0.0  0.0  0.0  0.0  0.0
 ...      ...  ...  ...  ...  ...  ...  ...
 195      4.0  2.0  0.0  3.0  0.0  0.0  0.0
 196      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 197      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 198      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 199      0.0  0.0  0.0  0.0  0.0  0.0  0.0

 [200 rows x 500 columns])

In [6]:
# Predicting All Missing Data in training set
imputed_train_ds = train_ds.values.copy()

# Your implementation to predict the missing values
(Put all your implementation for your algorithm in the following cell only to handle the missing values; )

In [7]:
## Put all your implementation for your solutioin in this cell only to predict the missing values; 
## NOTE 1: DO NOT change anything in the rest of the cells in this framework, 
## otherwise the changes might cause errors and make your implementation invalid.

## Note 2: 
## The user-item rating matrix is imputed_train_ds, 
## and the missing values are those 0s in imputed_train_ds. 
## You are required to predict them by using the solution in the given report. 

## The following parameters are required in the given report, 
## which is named "Effective Missing Data Prediction for Collaborative Filtering", 
## and you will need to use them. But, please do not change their values. 
LAMBDA = 0.7    # λ
GAMMA = 10      # γ
DELTA = 10      # δ
ITA = 0.7       # η
THETA = 0.7     # θ
EPSILON = 1e-9
n_items = df.item_id.unique().shape[0]
sim_items_set = np.zeros((n_items, n_items))
# n_users = df.user_id.unique().shape[0]
n_users= imputed_train_ds.shape[0]
sim_user_set = np.zeros((n_users, n_users))

for i, (user_i_vec,item_i_vec) in enumerate(zip(imputed_train_ds, imputed_train_ds.T)):
    for j, (user_j_vec,item_j_vec) in enumerate(zip(imputed_train_ds, imputed_train_ds.T)):
        
        # ratings corated by the current pair od users
        mask_i = user_i_vec > 0
        mask_j = user_j_vec > 0

        # corrated item index, skip if there are no corrated ratings
        corrated_index = np.intersect1d(np.where(mask_i), np.where(mask_j))
        if len(corrated_index) == 0:
            continue

        # average value of user_i_vec and user_j_vec
        mean_user_i = np.sum(user_i_vec) / (np.sum(np.clip(user_i_vec, 0, 1)) + EPSILON)
        mean_user_j = np.sum(user_j_vec) / (np.sum(np.clip(user_j_vec, 0, 1)) + EPSILON)

        # compute pearson corr
        user_i_sub_mean = user_i_vec[corrated_index] - mean_user_i
        user_j_sub_mean = user_j_vec[corrated_index] - mean_user_j

        r_ui_sub_r_i_sq = np.square(user_i_sub_mean)
        r_uj_sub_r_j_sq = np.square(user_j_sub_mean)

        r_ui_sum_sqrt = np.sqrt(np.sum(r_ui_sub_r_i_sq))
        r_uj_sum_sqrt = np.sqrt(np.sum(r_uj_sub_r_j_sq))

        sim = np.sum(user_i_sub_mean * user_j_sub_mean) / (r_ui_sum_sqrt * r_uj_sum_sqrt + EPSILON)

        # significance weighting
        weighted_sim = (min(len(corrated_index), GAMMA) / GAMMA) * sim
        
        #if weighted_sim > ITA:
        sim_user_set[i][j] = weighted_sim
            
      #items----------------------------------------------------------------------
        # ratings corated by the current pair of items
        mask_i = item_i_vec > 0
        mask_j = item_j_vec > 0

        # corrated index, skip if there are no corrated ratings
        corrated_index = np.intersect1d(np.where(mask_i), np.where(mask_j))
        if len(corrated_index) == 0:
            continue

        # average value of item_i_vec and item_j_vec
        mean_item_i = np.sum(item_i_vec) / (np.sum(np.clip(item_i_vec, 0, 1)) + EPSILON)
        mean_item_j = np.sum(item_j_vec) / (np.sum(np.clip(item_j_vec, 0, 1)) + EPSILON)

        # compute pearson corr
        item_i_sub_mean = item_i_vec[corrated_index] - mean_item_i
        item_j_sub_mean = item_j_vec[corrated_index] - mean_item_j

        r_ui_sub_ri_sq = np.square(item_i_sub_mean)
        r_uj_sub_rj_sq = np.square(item_j_sub_mean)

        r_ui_sub_ri_sq_sum_sqrt = np.sqrt(np.sum(r_ui_sub_ri_sq))
        r_uj_sub_rj_sq_sum_sqrt = np.sqrt(np.sum(r_uj_sub_rj_sq))

        sim = np.sum(item_i_sub_mean * item_j_sub_mean) / (r_ui_sub_ri_sq_sum_sqrt * r_uj_sub_rj_sq_sum_sqrt + EPSILON)

        # significance weighting
        weighted_sim = (min(len(corrated_index), DELTA) / DELTA) * sim
        
        # store prediction_mat calculation of items
        #if weighted_sim> THETA:         
        sim_items_set[i][j] = weighted_sim

prediction_mat = np.zeros((n_users, n_items))

for (i, j), rating in np.ndenumerate(imputed_train_ds):
           
    if rating == 0:
                                                
        #making similar users only be those that are greater than similarity threshhold
        sim_val_user = np.zeros(n_users)
        for k in range(1, len(sim_user_set[i])):
            if sim_user_set[i][k] > ITA:
                sim_val_user[k-1] = imputed_train_ds[i][k]
                
        sim_val_user = sim_val_user[sim_val_user != 0]
            
        sim_val_items = np.zeros(n_items)
        for k in range(1, len(sim_items_set[i])):
            if sim_items_set[i][k] > THETA:
                sim_val_items[k-1] = imputed_train_ds[i][k]
                
        sim_val_items = sim_val_items[sim_val_items != 0]
                
        # viable users and items from the sets 
        sim_user_ids = np.argsort(sim_user_set[i])[-(len(sim_val_user)+1):-1]
        sim_item_ids = np.argsort(sim_items_set[j])[-(len(sim_val_items)+1):-1]        

        #the average value of the current user
        sim_users = imputed_train_ds[sim_user_ids]
        sim_users_mean = np.sum(sim_users, axis=1) / (np.sum(np.clip(sim_users, 0, 1), axis=1) + EPSILON)
        user_mean = np.sum(imputed_train_ds[i]) / (np.sum(np.clip(imputed_train_ds[i], 0, 1)) + EPSILON)       
        
        # the average value of the current item's ratings
        sim_items = imputed_train_ds.T[sim_item_ids]
        sim_items_mean = np.sum(sim_items, axis=1) / (np.sum(np.clip(sim_items, 0, 1), axis=1) + EPSILON)
        item_mean = np.sum(imputed_train_ds.T[j]) / (np.sum(np.clip(imputed_train_ds.T[j], 0, 1)) + EPSILON)
        
        
        rated_items = sim_users[:, i] > 0
        
        # sim(u, v) * (r_vj - mean_v)
        
        sum_users = sim_val_user[rated_items] * (sim_users[rated_items, j] - sim_users_mean[rated_items])

        # sim(u, v) * (r_v - mean_v)
        
        sum_items = sim_val_items * (sim_items[:, i] - sim_items_mean)

        # filter unrated users and items
        sum_users *= np.clip(sim_users[rated_items, j], 0, 1)
        sum_items *= np.clip(sim_items[:, i], 0, 1)
        
        #caculating equations 8,9,10
        eq_9 = user_mean + (np.sum(sum_users) / (np.sum(sim_users[rated_items]) + EPSILON))
        eq_10 = item_mean + (np.sum(sum_items) / (np.sum(sim_items) + EPSILON))
        eq_8 = LAMBDA * eq_9 + (LAMBDA-1) * eq_10
        
        #check if S(u) and S(i) are empty
        check1 = False
        check2= False
        if len(sim_users) > 0:
            check1 = True          
        if len(sim_items) > 0:
            check2= True
        
        if check1 == True and check2== True:               
            prediction_mat[i][j] = eq_8
        elif check1 == True:
            prediction_mat[i][j] = eq_9              
        elif check2== True:
            prediction_mat[i][j] = eq_10

    else: 
        prediction_mat[i][j] = rating
                
imputed_train_ds = prediction_mat

# Evaluation

### Compute Pearson Correlation Coefficient of All Pairs of Items between active set and imputed training set

In [8]:
imputed_train_ds = pd.DataFrame(imputed_train_ds)
imputed_train_ds

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
0,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,0.000000,3.000000,0.000000
1,1.336180,2.000000,1.311823,4.000000,1.499483,4.000000,4.000000,1.473355,1.706196,2.000000,...,1.659578,4.000000,4.000000,1.382934,3.000000,3.000000,1.864680,1.504176,1.713490,1.671823
2,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,4.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,4.000000,0.000000,5.000000,0.000000,0.000000,3.000000,4.000000,2.000000,0.000000,2.000000,...,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,0.000000,0.000000
4,3.000000,3.481481,4.000000,3.861538,3.574468,3.000000,2.000000,2.000000,2.844130,5.000000,...,3.040816,4.000000,3.951220,3.962963,3.227273,2.305556,2.357143,3.558824,2.861111,3.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,3.393617,3.393617,3.393617,3.393617,3.393617,3.393617,3.393617,5.000000,4.000000,5.000000,...,3.393617,3.393617,4.000000,3.393617,4.000000,2.000000,3.000000,3.393617,3.393617,3.393617
296,0.000000,0.000000,5.000000,4.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
297,4.000000,3.545455,3.000000,3.545455,3.545455,3.545455,3.545455,3.545455,3.545455,3.545455,...,3.545455,3.545455,3.545455,3.545455,3.545455,3.545455,3.545455,3.545455,3.545455,3.545455
298,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,4.000000,0.000000,0.000000,...,0.000000,0.000000,5.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000
299,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,3.000000,0.000000,...,4.000000,0.000000,0.000000,5.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000

In [9]:
active_user_pearson_corr = np.zeros((active_ds.shape[0], train_ds.shape[0]))

# Compute Pearson Correlation Coefficient of All Pairs of Users between active set and imputed training set
for i, user_i_vec in enumerate(active_ds.values):
    for j, user_j_vec in enumerate(imputed_train_ds.values):
        
        # ratings corated by the current pair od users
        mask_i = user_i_vec > 0
        mask_j = user_j_vec > 0

        # corrated item index, skip if there are no corrated ratings
        corrated_index = np.intersect1d(np.where(mask_i), np.where(mask_j))
        if len(corrated_index) == 0:
            continue

        # average value of user_i_vec and user_j_vec
        mean_user_i = np.sum(user_i_vec) / (np.sum(np.clip(user_i_vec, 0, 1)) + EPSILON)
        mean_user_j = np.sum(user_j_vec) / (np.sum(np.clip(user_j_vec, 0, 1)) + EPSILON)

        # compute pearson corr
        user_i_sub_mean = user_i_vec[corrated_index] - mean_user_i
        user_j_sub_mean = user_j_vec[corrated_index] - mean_user_j

        r_ui_sub_r_i_sq = np.square(user_i_sub_mean)
        r_uj_sub_r_j_sq = np.square(user_j_sub_mean)

        r_ui_sum_sqrt = np.sqrt(np.sum(r_ui_sub_r_i_sq))
        r_uj_sum_sqrt = np.sqrt(np.sum(r_uj_sub_r_j_sq))

        sim = np.sum(user_i_sub_mean * user_j_sub_mean) / (r_ui_sum_sqrt * r_uj_sum_sqrt + EPSILON)

        # significance weighting
        weighted_sim = (min(len(corrated_index), GAMMA) / GAMMA) * sim

        active_user_pearson_corr[i][j] = weighted_sim

active_user_pearson_corr

array([[ 0.19867985, -0.13616358,  0.20328741, ...,  0.22646205,
         0.0185801 ,  0.14137305],
       [-0.3666931 ,  0.29806928, -0.22990135, ...,  0.24912767,
         0.2       , -0.1880672 ],
       [ 0.1       , -0.30183301, -0.08077397, ..., -0.04773344,
        -0.12560385,  0.12029024],
       ...,
       [-0.054453  ,  0.19026039,  0.46204078, ..., -0.01313415,
         0.02904206,  0.36265682],
       [ 0.29194178,  0.08634232,  0.40987056, ..., -0.16903427,
        -0.14253632, -0.03635009],
       [-0.32879797,  0.02544426,  0.0078519 , ..., -0.05889149,
         0.14904826, -0.29097566]])

## Predict Ratings of Testing Set

In [10]:
K = 10

test_ds_pred = np.zeros_like(test_ds.values)

for (i, j), rating in np.ndenumerate(test_ds.values):

    if rating > 0:

        sim_user_ids = np.argsort(active_user_pearson_corr[i])[-1:-(K + 1):-1]

        #==================user-based==================#
        # the coefficient values of similar users
        sim_val = active_user_pearson_corr[i][sim_user_ids]

        # the average value of the current user's ratings
        sim_users = imputed_train_ds.values[sim_user_ids]
        user_mean = np.sum(active_ds.values[i]) / (np.sum(np.clip(active_ds.values[i], 0, 1)) + EPSILON)
        sim_user_mean = np.sum(sim_users, axis=1) / (np.sum(np.clip(sim_users, 0, 1), axis=1) + EPSILON)

        # select the users who rated item j
        mask_rated_j = sim_users[:, j] > 0
        
        # sim(u, v) * (r_vj - mean_v)
        sim_r_sum_mean = sim_val[mask_rated_j] * (sim_users[mask_rated_j, j] - sim_user_mean[mask_rated_j])
        
        user_based_pred = user_mean + np.sum(sim_r_sum_mean) / (np.sum(sim_val[mask_rated_j]) + EPSILON)
        user_based_pred = np.clip(user_based_pred, 0, 5)

        test_ds_pred[i][j] = user_based_pred
        
test_ds_pred

#implement algorithm

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [4.20510385, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 4.26068116, 0.        , ..., 0.        , 0.        ,
        0.        ]])

## Compute MAE and RMSE

In [11]:
# MAE
MAE = np.sum(np.abs(test_ds_pred - test_ds.values)) / np.sum(np.clip(test_ds.values, 0, 1))

# RMSE
RMSE = np.sqrt(np.sum(np.square(test_ds_pred - test_ds.values)) / np.sum(np.clip(test_ds.values, 0, 1)))

print("MAE: {}, RMSE: {}" .format(MAE, RMSE))

MAE: 0.7666484523355108, RMSE: 0.9855594474313758